deploy:
  runs-on: windows-latest
  needs: test  # Runs only if tests are successful

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy locally
      shell: pwsh
      run: |
        $destination = 'C:\Users\Sowmyasree\Documents\deployment'
        
        # Ensure the destination directory exists
        if (!(Test-Path -Path $destination)) {
          New-Item -ItemType Directory -Path $destination
        }
        
        # Clear the destination directory
        Remove-Item -Path "$destination\*" -Recurse -Force

        # Copy files to the destination
        Copy-Item -Path .\* -Destination $destination -Recurse -Force
